### ISSUE TITLE
node/socket.io ('node_js') datasource plugin not working

### ISSUE THREAD

**Issue by jritsema** [Freeboard/plugins#7]
I just followed the [readme](https://github.com/Freeboard/plugins/blob/master/datasources/plugin_nodejs_sample/README.md) and tested this plugin out and it doesn't appear to work anymore.  Tested on:
- latest freeboad as of 2/29/16
- node v0.12.2
- socket.io v1.4.5

Has anyone else tried to get this working lately?  @hugocore ?

Also, it appears that this repo is no longer active?  I submitted a PR over 6 months ago with additional plugins and never heard back.  Anyone out there??

**Comment by jritsema** [comment]
I figured it out.  Turns out the [sample dashboard .json file](https://github.com/Freeboard/plugins/blob/master/datasources/plugin_nodejs_sample/plugin_node_sample_config.json) was missing the `events` property.  This property did exist in the [.html file](https://github.com/Freeboard/plugins/blob/master/datasources/plugin_nodejs_sample/plugin_node_sample_client.html) though.

**Comment by hugocore** [comment]
Thanks for the heads up @jritsema.

I created a PR to fix this issue.
